spring.application.name=webshop-automation
spring.profiles.active=prod

server.servlet.context-path=/api

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver


spring.ai.ollama.init.pull-model-strategy=when_missing
spring.ai.ollama.init.max-retries=3
spring.ai.ollama.init.timeout=10m
spring.ai.ollama.embedding.options.keep-alive=30m
spring.ai.ollama.embedding.model=nomic-embed-text

spring.ai.openai.api-key=
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.2

products.collection=normalize-competitor-products
products.search.limit=3

matching-step.exact.disabled=true
matching-step.embedding.disabled=true
matching-step.gpt.disabled=true