server.host=5.199.138.20
server.port=3344

vector-bd.qdrant.url=http://${server.host}:6333

spring.datasource.url=jdbc:postgresql://${server.host}:5432/webshop-automation-db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.ai.ollama.base-url=http://${server.host}:11434