server.host=localhost
server.port=8080

vector-bd.qdrant.url=http://5.199.138.20:6333

spring.datasource.url=jdbc:postgresql://${server.host}:5432/webshop-automation-db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.ai.ollama.base-url=http://5.199.138.20:11434