server.host=${SERVER_HOST_DEV:localhost}
server.port=${DEV_API_PORT:8080}

vector-bd.qdrant.url=http://${SERVER_HOST_PROD}:6333

spring.datasource.url=jdbc:postgresql://${SERVER_HOST_DEV:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:webshop-automation-db}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}

spring.ai.ollama.base-url=http://${SERVER_HOST_PROD}:${OLLAMA_PORT}